services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin1234"
      MYSQL_DATABASE: "daily-diet-api"
      MYSQL_ROOT_PASSWORD: "admin1234"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /Users/dcuchas/ignite/pythonzin/desafio_2/daily_diet_api_docker_volumes/mysql:/var/lib/mysql